---
title: "p8105_hw6_yc4016"
output: github_document
date: "2022-12-01"
author: "Yishan Chen"
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(modelr)
library(mgcv)

set.seed(1)
```


# Problem 2
```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv") %>% 
  mutate(city_state = str_c(city, state, sep = ", ", collapse = NULL),
         homicide_situation = as.numeric(disposition == "Closed by arrest")) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")),
         victim_race %in% c("White", "Black")) %>% 
  mutate (victim_age = as.numeric(victim_age),
          homicide_situation = as.numeric(homicide_situation))
  
homicide_df
```


```{r}
fit_logistic_baltimore = 
  homicide_df %>% 
  filter(city_state == "Baltimore, MD") %>%
  glm(homicide_situation ~ victim_age + victim_sex + victim_age, data = ., family = binomial()) 

fit_logistic_baltimore
```


```{r}
fit_logistic_baltimore %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         lower_bound = exp(estimate - 1.96 * std.error),
         upper_bound = exp(estimate + 1.96 * std.error)) %>%
  select(term, estimate, OR, lower_bound, upper_bound) %>%
  filter(term == "victim_sexMale") %>% 
  knitr::kable(digits = 3)
```


```{r}
fit_logistic_all =
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(models = map(data, ~glm(homicide_situation ~ victim_age + victim_sex + victim_age, data = .x, family = binomial())),
         results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  mutate(OR = exp(estimate),
         lower_bound = exp(estimate - 1.96 * std.error),
         upper_bound = exp(estimate + 1.96 * std.error)) %>%
  filter(term == "victim_sexMale") %>% 
  select(city_state, OR, lower_bound, upper_bound)

fit_logistic_all

fit_logistic_all %>% 
    knitr::kable(digits = 3)
```


```{r}
plot = 
  fit_logistic_all %>% 
    mutate(city_state = fct_reorder(city_state, OR)) %>% 
    ggplot(aes(x = city_state, y = OR, color = city_state)) + 
    geom_point() + 
    geom_errorbar(aes(ymin = lower_bound, ymax = upper_bound)) + 
    theme(axis.text.x = element_text(angle=90, hjust = 1)) + 
    labs(x = "City_states",
         y = "Estimated OR",
         title = "Estimated ORs with CIs for all cities for homicides comparing male/female victims") +
         theme(legend.position = "none") 

plot
```




# Problem 3

```{r}
birthweight = 
  read_csv("data/birthweight.csv")
```

